baseurl = "https://www.btsh.org.tw/"
title = "北投社區安全家庭互助協會 Beitou Safe Home Association"
#author = ""
languagecode = "zh-Hant-TW"
paginate = 3
theme = "hugo-renga"

enableEmoji = false
hasCJKLanguage = true
enableRobotsTXT = true
disableHugoGeneratorInject = true

googleAnalytics = "UA-105725051-1"
# disqusShortname = "your-disqus-shortname"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[markup.goldmark.renderer]
unsafe= true

[params]
pagetitle = "北投安家"
copyright = "北投社區安全家庭互助協會"
copyrightUrl = "/contact/"
faviconfile = "img/favicon.png"
logofile = "img/btsh-logo.svg"
posterfile = ""
posts_navigation = true
uselatex = false
highlightjs = false
progressively = false

facebook = "beitousafehome"
# github = ""
# twitter = ""
# linkedin = ""
# email = ""

[[menu.primary]]
identifier = "home"
name = "首頁"
url = "/"
weight = 1

[[menu.primary]]
identifier = "story"
name = "故事"
url = "/story/"
weight = 2

[[menu.primary]]
identifier = "donate"
name = "支持"
url = "/donate/"
weight = 3

[[menu.primary]]
identifier = "contact"
name = "聯絡"
url = "/contact/"
weight = 4
